services:
  postgres:
    image: postgres:16-alpine
    container_name: whisper-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: whisper
      POSTGRES_DB: whisper_identity_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # MongoDB: Повідомлення, Медіа-метадані
  mongodb:
    image: mongo:latest
    container_name: whisper-mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: whisper
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata: